---
# Create a security group
- name: Create a security group
  openstack.cloud.security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ security_groups }}' # loop through 'security_groups' defined in host_vars/base_vars.yaml

- name: Create a list of security group names
  ansible.builtin.set_fact:
    sg_names: '{{ sg_names|default([]) + [ item.name ] }}'
  loop: '{{ security_groups }}'

# Create security group rules
- name: Create security group rules
  openstack.cloud.security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ item.remote_ip_prefix }}'
    state: present
  loop: '{{ security_group_rules }}' # 'security_groups_rules' defined in host_vars/base_vars.yaml

# Use debug module to print message when security groups have been created
- ansible.builtin.debug:
    msg: "Security group(s) {{ sg_names }} have been created."