- name: Delete project content & directory
  file:
    path: ~/data/CCC_A2
    state: absent

- name: ensure pexpect is installed in the playbook python
  pip:
    name: pexpect
    state: present

# Clone source code repository
- name: Clone source code repository into project directory
  git:
    repo: "https://github.com/CCC-Team5/CCC_A2.git"
    dest: ~/data/CCC_A2
  become: true