version: "3"
services:
  backend_container:
    image: tweet_backend
    build: ./tweet_harv_backend
    ports: 
      - "8000:8000"
  
  frontend_container:
    image: tweet_frontend
    build: ./tweet_harv_app
    ports:
      - "1313:1313"