######################
# under construction #
######################

- hosts: localhost
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

# Install Docker and CouchDB
- hosts: couchdbs
  vars_files:
    - host_vars/couchdb.yaml
  gather_facts: true

  roles:
  - role: common
  - role: install-docker
  # - role: mount-volume #
  # - role: setup-db #

# # CouchDB configuration
# - hosts: couchdbs:!master
#   vars_files:
#     - host_vars/couchdb.yaml
#   gather_facts: true

#   roles:
#   - role:

# # Install Tweet-Harvester
# - hosts: DataNodes
#   vars_files:
#     - host_vars/env_vars.yaml
#   gather_facts: true

#   roles:
#     - role: 
