- name: Build main app docker image
  become: yes
  args:
    warn: false
  command: 'docker build -t tweet_frontend /data/grp5_application/CCC_A2/tweet_harv_app/'

# Stop existing and remove docker containers (if any)
- name: Stop frontend docker container
  become: yes
  docker_container:
    name: tweet_frontend
    state: absent

- name: Start docker frontend image
  become: yes
  args:
    warn: false
  command: 'docker run --restart=on-failure:15 -d -p 1313:1313 tweet_frontend'