# Part of Assignment 2 - Cluster and Cloud Computing (COMP90024) Group 5

# Author:

# Xinhao Chen 1230696 Melbourne
# Weimin Ouyang 340438 Melbourne
# Tianqi Yu 1221167 China
# Junjie Xia 1045673 China
# Yuling Zheng 954408 Melbourne

# Stop existing and remove docker containers (if any)
- name: remove frontend docker container
  become: yes
  docker_container:
    name: ccc_a2_frontend_container_1
    state: absent

- name: remove frontend docker image
  become: yes
  args:
    warn: false
  command: 'docker image rm -f tweet_frontend'

- name: run docker compose
  become: yes
  docker_compose:
    project_src: "~/data/CCC_A2/"
    files:
      - docker-compose.yml
    pull: false
    build: yes
    state: present
    recreate: always

# - name: Build frontend docker image
#   become: yes
#   args:
#     warn: false
#   command: 'docker build -t tweet_frontend ~/data/CCC_A2/tweet_harv_app/'


# - name: Start docker frontend image
#   become: yes
#   args:
#     warn: false
#   command: 'docker run --name frontend_container --restart=on-failure:15 -d -p 0.0.0.0:1313:1313 tweet_frontend'
