
---
- name: Gather facts of remote host
  ansible.builtin.setup:
    gather_subset: all

# Install dependencies on the host

- name: Install dependencies
  tags: always
  become: yes
  ansible.builtin.apt:
    name: ['apt-transport-https', 'build-essential', 'ca-certificates', 'curl', 'git', 'python3-dev', 'python3-pip', 'python3-setuptools', 'software-properties-common', 'unzip', 'vim']
    state: latest
    install_recommends: no
    update_cache: yes
  environment: '{{ proxy }}'
# sudo apt-get update && sudo apt-get install python3-dev python3-setuptools python-pip

- name: Update pip
  tags: always
  become: yes
  ansible.builtin.pip:
    name: ['pip', 'openstacksdk']
    state: latest
  environment: '{{ proxy }}'
# pip install --upgrade pip && pip install openstacksdk
