- hosts: localhost
  vars_files:
    - host_vars/base_vars.yaml
  gather_facts: true

# Order is important:
# install common packages first
# then volumn, then security-group
# Finally instance
  roles:
    - role: base-common
    - role: base-volume
    - role: base-security-group
    - role: base-instance