# Part of Assignment 2 - Cluster and Cloud Computing (COMP90024) Group 5

# Author:

# Xinhao Chen 1230696 Melbourne
# Weimin Ouyang 340438 Melbourne
# Tianqi Yu 1221167 China
# Junjie Xia 1045673 China
# Yuling Zheng 954408 Melbourne

- hosts: localhost
  vars_files:
    - host_vars/base_vars.yaml
  gather_facts: true

# Order is important:
# install common packages first
# then volumn, then security-group
# Finally instance
  roles:
    - role: base-common
    - role: base-volume
    - role: base-security-group
    - role: base-instance
