# Part of Assignment 2 - Cluster and Cloud Computing (COMP90024) Group 5

# Author:

# Xinhao Chen 1230696 Melbourne
# Weimin Ouyang 340438 Melbourne
# Tianqi Yu 1221167 China
# Junjie Xia 1045673 China
# Yuling Zheng 954408 Melbourne

---
- name: Uninstall old versions of docker
  become: yes
  ansible.builtin.apt:
    name: ['docker', 'docker-engine', 'docker.io']
    state: absent

- name: Install dependencies
  become: yes
  ansible.builtin.apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'python-setuptools', 'software-properties-common']
    state: latest
    install_recommends: no
    update_cache: yes
  environment: "{{ proxy }}"

- name: Add Docker apt repository key
  become: yes
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  environment: "{{ proxy }}"

- name: Add Docker apt repository and update apt cache
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    mode: '644'
    update_cache: yes
    state: present
  environment: "{{ proxy }}"

- name: Install docker
  become: yes
  ansible.builtin.apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: latest
    install_recommends: no
    update_cache: yes
  environment: "{{ proxy }}"

- name: Install docker-compose
  become: yes
  ansible.builtin.pip:
    name: ['docker-compose']
    state: latest
  environment: "{{ proxy }}"

# docker proxy config
- name: Create proxy directory
  become: yes
  ansible.builtin.file:
    path: '/etc/systemd/system/docker.service.d'
    state: directory
    owner: 'root'
    group: 'root'
    recurse: yes
    state: directory
  

- name: Create proxy file
  become: yes
  ansible.builtin.file:
    path: '/etc/systemd/system/docker.service.d/http-proxy.conf'
    state: touch

- name: Add proxy
  become: yes
  ansible.builtin.blockinfile:
    path: '/etc/systemd/system/docker.service.d/http-proxy.conf'
    block: |
      [Service]
      proxy = 'HTTP_PROXY: http://wwwproxy.unimelb.edu.au:8000/' 'HTTPS_PROXY: http://wwwproxy.unimelb.edu.au:8000/' 'http_proxy: http://wwwproxy.unimelb.edu.au:8000/' 'https_proxy: http://wwwproxy.unimelb.edu.au:8000/' 'no_proxy: localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.u nimelb.edu.au,.cloud.unimelb.edu.au'

# restart systemd daemons
- name: Reload systemd daemons
  become: yes
  command: systemctl daemon-reload

# restart docker
- name: Restart docker
  become: yes
  command: systemctl restart docker


