# Part of Assignment 2 - Cluster and Cloud Computing (COMP90024) Group 5

# Author:

# Xinhao Chen 1230696 Melbourne
# Weimin Ouyang 340438 Melbourne
# Tianqi Yu 1221167 China
# Junjie Xia 1045673 China
# Yuling Zheng 954408 Melbourne

couch_cluster_server:
  - '172.26.134.129'
  - '172.26.129.71'
  - '172.26.130.21'
  - '172.26.134.2'
