# Part of Assignment 2 - Cluster and Cloud Computing (COMP90024) Group 5

# Author:

# Xinhao Chen 1230696 Melbourne
# Weimin Ouyang 340438 Melbourne
# Tianqi Yu 1221167 China
# Junjie Xia 1045673 China
# Yuling Zheng 954408 Melbourne

volumes:
  - device: /dev/vdb
    mountpoint: /data
  - device: /dev/vdc
    mountpoint: /var/lib/docker

user: grp5admin
pass: password
cookie: 'grp5mendes'
uuid: '6ea1e6ed41faafe7a5493ca56b00a055'
