# Part of Assignment 2 - Cluster and Cloud Computing (COMP90024) Group 5

# Author:

# Xinhao Chen 1230696 Melbourne
# Weimin Ouyang 340438 Melbourne
# Tianqi Yu 1221167 China
# Junjie Xia 1045673 China
# Yuling Zheng 954408 Melbourne

# Stop existing and remove docker containers (if any)
- name: remove backend docker container
  become: yes
  docker_container:
    name: ccc_a2_backend_container_1
    state: absent

- name: remove backend docker image
  become: yes
  args:
    warn: false
  command: 'docker image rm -f tweet_backend'

# # Build Docker image for tweet harvester
# - name: Build backend image and put it in project repo
#   become: yes
#   args:
#     warn: false
#   command: 'docker build -t tweet_backend ~/data/CCC_A2/tweet_harv_backend/'

# - name: Start docker image (tweet_backend)
#   become: yes
#   args:
#     warn: false
#   command: 'docker run --name backend_container --restart=on-failure:15 -d -p 0.0.0.0:8000:8000 tweet_backend'
