- name: register cluster nodes with master
  shell: 'curl -X POST -H "Content-Type: application/json" http://grp5admin:password@localhost:5984/_cluster_setup -d ''{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "grp5admin", "password":"password", "port": 5984, "node_count": "4", "remote_node": "{{ item }}", "remote_current_user": "grp5admin", "remote_current_password": "password", "remote_port":5984 }'''
  args:
    warn: false
  loop: "{{ couch_cluster_server }}"

- name: add node in cluster
  shell: 'curl -X POST -H "Content-Type: application/json" http://grp5admin:password@localhost:5984/_cluster_setup -d ''{"action": "add_node", "host":"{{ item }}", "port": 5984, "username": "grp5admin", "password":"password"}'''
  args:
    warn: false
  loop: "{{ couch_cluster_server }}"

- name: complete cluster setup
  args:
    warn: false
  shell: 'curl -X POST -H "Content-Type: application/json" http://grp5admin:password@localhost:5984/_cluster_setup -d ''{"action": "finish_cluster"}'''