- name: System Update
  become: yes
  apt:
    update_cache: yes
    upgrade: dist

- name: Setup Build Environment
  become: yes
  apt:
    name: 
      - build-essential 
      - pkg-config 
      - erlang 
      - libicu-dev
      - couch-libmozjs185-dev 
      - libcurl4-openssl-dev
    state: latest
    install_recommends: no

- name: Download CouchDB
  become: yes
  get_url:
    url: https://archive.apache.org/dist/couchdb/source/3.2.0/apache-couchdb-3.2.0.tar.gz
    dest: /usr/local/src # download couchdb to this directory

- name: Unpack CouchDB Source
  become: yes
  unarchive:
    src: /usr/local/src/apache-couchdb-3.2.0.tar.gz
    dest: /usr/local/src
    remote_src: yes

- name: Configure Build
  become: yes
  command: chdir=/usr/local/src/apache-couchdb-3.2.0 ./configure

- name: Make Build
  become: yes
  make:
    chdir: /usr/local/src/apache-couchdb-3.2.0
    target: release

- name: Deploy CouchDB #Copy couchdb to /data repository#
  become: yes
  command: cp -R /usr/local/src/apache-couchdb-3.2.0/rel/couchdb /data/

- name: Add CouchDB System Account
  become: yes
  user:
    name: couchdb
    comment: "CouchDB System Account"
    shell: /bin/bash
    system: yes
    home: /data/couchdb
    createhome: no

- name: Change CouchDB Ownership
  become: yes
  file:
    path: /data/couchdb
    owner: couchdb
    group: couchdb
    mode: 0770
    recurse: yes
    state: directory

- name: Change CouchDB Config File Permission
  become: yes
  file:
    path: /data/couchdb/etc
    owner: couchdb
    group: couchdb
    mode: 0644
    recurse: yes
    state: directory

- name: Change CouchDB Directory Permission 
  become: yes
  command: find /data/couchdb -type d -exec chmod 0770 {} \; ## find all directorys in /couchdb and chmod them to 0770

- name: Change Node Name
  become: yes
  replace:
    dest: /data/couchdb/etc/vm.args
    regexp: '^-name couchdb@localhost$'
    replace: '-name couchdb@{{ansible_eth0.ipv4.address}}'

- name: Add kernel Args
  blockinfile:
    dest: /data/couchdb/etc/vm.args
    insertafter: '-kernel'
    content: | 
      -kernel inet_dist_listen_min 9100
      -kernel inet_dist_listen_max 9200

- name: Set Cookie
  become: yes
  replace:
    dest: /data/couchdb/etc/vm.args
    regexp: '^-setcookie monster$'
    replace: '-setcookie grp5mendes'

- name: Bind Cluster/Node Address to Public
  become: yes
  copy:
    src: ./files/local.ini
    dest: /data/couchdb/etc

- name: Add Admin User
  become: yes
  lineinfile:
    dest: /data/couchdb/etc/local.ini
    insertafter: '^\[admins\]$'
    line: 'grp5admin = password'

- name: Install CouchDB Serice
  become: yes
  copy:
    src: ./files/couchdb.service
    dest: /etc/systemd/system/couchdb.service
    owner: root
    group: root

- name: Enable CouchDB Service
  become: yes
  systemd:
    daemon-reload: yes
    name: couchdb
    enabled: yes

- name: Start CouchDB Service
  become: yes
  systemd:
    name: couchdb
    state: restarted