# Part of Assignment 2 - Cluster and Cloud Computing (COMP90024) Group 5

# Author:

# Xinhao Chen 1230696 Melbourne
# Weimin Ouyang 340438 Melbourne
# Tianqi Yu 1221167 China
# Junjie Xia 1045673 China
# Yuling Zheng 954408 Melbourne
---
- name: Gather facts of remote host
  setup:
    gather_subset: all
  
# Install dependencies on the host
- name: Install dependencies
  become: yes
  ansible.builtin.apt:
    name: ['vim','unzip','git','python3-dev', 'python3-setuptools', 'python3-pip','software-properties-common']
    state: latest
    install_recommends: no
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update && sudo apt-get install python3-dev python3-setuptools python-pip

- name: Update pip
  ansible.builtin.pip:
    name: ['pip', 'openstacksdk']
    state: latest
# pip install --upgrade pip && pip install openstacksdk
