# Part of Assignment 2 - Cluster and Cloud Computing (COMP90024) Group 5

# Author:

# Xinhao Chen 1230696 Melbourne
# Weimin Ouyang 340438 Melbourne
# Tianqi Yu 1221167 China
# Junjie Xia 1045673 China
# Yuling Zheng 954408 Melbourne

# Stop existing and remove docker containers (if any)
- name: remove harv docker container
  become: yes
  docker_container:
    name: harvester_container
    state: absent

- name: remove harvester docker image
  become: yes
  args:
    warn: false
  command: 'docker image rm -f twitter_harv'

- name: Build harv docker image
  become: yes
  args:
    warn: false
  command: 'docker build -t twitter_harv ~/data/CCC_A2/twitter-harvester/'

- name: Start docker harvester image
  become: yes
  args:
    warn: false
  command: 'docker run --name harvester_container --restart=on-failure:100 -d twitter_harv'
