# Stop existing and remove docker containers (if any)
- name: remove harv docker container
  become: yes
  docker_container:
    name: harvester_container
    state: absent

- name: remove backend docker image
  become: yes
  args:
    warn: false
  command: 'docker image rm -f twitter_harv'

- name: Build harv docker image
  become: yes
  args:
    warn: false
  command: 'docker build -t tweet_harv ~/data/CCC_A2/twitter-harvester/'

- name: Start docker harvester image
  become: yes
  args:
    warn: false
  command: 'docker run --name harvester_container --restart=on-failure:15 -d tweet_harv'