# Part of Assignment 2 - Cluster and Cloud Computing (COMP90024) Group 5

# Author:

# Xinhao Chen 1230696 Melbourne
# Weimin Ouyang 340438 Melbourne
# Tianqi Yu 1221167 China
# Junjie Xia 1045673 China
# Yuling Zheng 954408 Melbourne

- hosts: Webservers
  vars_files:
    - host_vars/depend_vars.yaml
  gather_facts: true

  roles:
    - role: depend-common
    - role: depend-mount-volume
    - role: depend-install-docker
    - role: depend-install-couchdb
